[package]
name = "uwuify"
version = "0.1.0"
authors = ["c0deb0t <daniel.liu02@gmail.com>"]
edition = "2018"
license = "MIT"
description = "fastest text uwuifier in the west"
repository = "https://github.com/Daniel-Liu-c0deb0t/uwu"
readme = "README.md"
keywords = ["SIMD", "uwu", "owo", "cli"]
categories = ["algorithms", "hardware-support", "text-processing", "command-line-utilities"]

[dependencies]
clap = "^2.33"
parking_lot = "^0.11"

[profile.release]
lto = true

[lib]
name = "uwuifier"
path = "src/lib.rs"

[[bin]]
name = "uwuify"
path = "src/main.rs"
