[package]
name = "uwu"
version = "0.1.0"
authors = ["c0deb0t <daniel.liu02@gmail.com>"]
edition = "2018"

[dependencies]
clap = "^2.33"
parking_lot = "^0.11"

[profile.release]
lto = true

[lib]
name = "uwu_ifier"
path = "src/lib.rs"

[[bin]]
name = "uwu"
path = "src/main.rs"
